[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
fuel-block-committer-encoding = { git = "https://github.com/FuelLabs/fuel-block-committer", branch = "feat/blob_metadata" }
hex = "0.4.3"
